namespace rec WebGPU
open System
#nowarn "9"
type RequestAdapterStatus =
    | Success = 1
    | InstanceDropped = 2
    | Unavailable = 3
    | Error = 4
    | Unknown = 5
type AdapterType =
    | DiscreteGPU = 1
    | IntegratedGPU = 2
    | CPU = 3
    | Unknown = 4
type AddressMode =
    | Undefined = 0
    | ClampToEdge = 1
    | Repeat = 2
    | MirrorRepeat = 3
type BackendType =
    | Undefined = 0
    | Null = 1
    | WebGPU = 2
    | D3D11 = 3
    | D3D12 = 4
    | Metal = 5
    | Vulkan = 6
    | OpenGL = 7
    | OpenGLES = 8
type BufferBindingType =
    | Undefined = 0
    | Uniform = 1
    | Storage = 2
    | ReadOnlyStorage = 3
type SamplerBindingType =
    | Undefined = 0
    | Filtering = 1
    | NonFiltering = 2
    | Comparison = 3
type TextureSampleType =
    | Undefined = 0
    | Float = 1
    | UnfilterableFloat = 2
    | Depth = 3
    | Sint = 4
    | Uint = 5
type StorageTextureAccess =
    | Undefined = 0
    | WriteOnly = 1
    | ReadOnly = 2
    | ReadWrite = 3
type BlendFactor =
    | Undefined = 0
    | Zero = 1
    | One = 2
    | Src = 3
    | OneMinusSrc = 4
    | SrcAlpha = 5
    | OneMinusSrcAlpha = 6
    | Dst = 7
    | OneMinusDst = 8
    | DstAlpha = 9
    | OneMinusDstAlpha = 10
    | SrcAlphaSaturated = 11
    | Constant = 12
    | OneMinusConstant = 13
    | Src1 = 14
    | OneMinusSrc1 = 15
    | Src1Alpha = 16
    | OneMinusSrc1Alpha = 17
type BlendOperation =
    | Undefined = 0
    | Add = 1
    | Subtract = 2
    | ReverseSubtract = 3
    | Min = 4
    | Max = 5
type OptionalBool =
    | False = 0
    | True = 1
    | Undefined = 2
type BufferMapAsyncStatus =
    | Success = 1
    | InstanceDropped = 2
    | ValidationError = 3
    | Unknown = 4
    | DeviceLost = 5
    | DestroyedBeforeCallback = 6
    | UnmappedBeforeCallback = 7
    | MappingAlreadyPending = 8
    | OffsetOutOfRange = 9
    | SizeOutOfRange = 10
type MapAsyncStatus =
    | Success = 1
    | InstanceDropped = 2
    | Error = 3
    | Aborted = 4
    | Unknown = 5
type BufferMapState =
    | Unmapped = 1
    | Pending = 2
    | Mapped = 3
[<Flags>]
type BufferUsage =
    | None = 0L
    | MapRead = 1L
    | MapWrite = 2L
    | CopySrc = 4L
    | CopyDst = 8L
    | Index = 16L
    | Vertex = 32L
    | Uniform = 64L
    | Storage = 128L
    | Indirect = 256L
    | QueryResolve = 512L
[<Flags>]
type ColorWriteMask =
    | None = 0L
    | Red = 1L
    | Green = 2L
    | Blue = 4L
    | Alpha = 8L
    | All = 15L
type CompareFunction =
    | Undefined = 0
    | Never = 1
    | Less = 2
    | Equal = 3
    | LessEqual = 4
    | Greater = 5
    | NotEqual = 6
    | GreaterEqual = 7
    | Always = 8
type CompilationInfoRequestStatus =
    | Success = 1
    | InstanceDropped = 2
    | Error = 3
    | DeviceLost = 4
    | Unknown = 5
type CompilationMessageType =
    | Error = 1
    | Warning = 2
    | Info = 3
type CompositeAlphaMode =
    | Auto = 0
    | Opaque = 1
    | Premultiplied = 2
    | Unpremultiplied = 3
    | Inherit = 4
type AlphaMode =
    | Opaque = 1
    | Premultiplied = 2
    | Unpremultiplied = 3
type CreatePipelineAsyncStatus =
    | Success = 1
    | InstanceDropped = 2
    | ValidationError = 3
    | InternalError = 4
    | DeviceLost = 5
    | DeviceDestroyed = 6
    | Unknown = 7
type CullMode =
    | Undefined = 0
    | None = 1
    | Front = 2
    | Back = 3
type DeviceLostReason =
    | Unknown = 1
    | Destroyed = 2
    | InstanceDropped = 3
    | FailedCreation = 4
type PopErrorScopeStatus =
    | Success = 1
    | InstanceDropped = 2
type ErrorFilter =
    | Validation = 1
    | OutOfMemory = 2
    | Internal = 3
type ErrorType =
    | NoError = 1
    | Validation = 2
    | OutOfMemory = 3
    | Internal = 4
    | Unknown = 5
    | DeviceLost = 6
type LoggingType =
    | Verbose = 1
    | Info = 2
    | Warning = 3
    | Error = 4
type ExternalTextureRotation =
    | Rotate0Degrees = 1
    | Rotate90Degrees = 2
    | Rotate180Degrees = 3
    | Rotate270Degrees = 4
type Status =
    | Success = 1
    | Error = 2
type SharedFenceType =
    | VkSemaphoreOpaqueFD = 1
    | SyncFD = 2
    | VkSemaphoreZirconHandle = 3
    | DXGISharedHandle = 4
    | MTLSharedEvent = 5
type FeatureName =
    | DepthClipControl = 1
    | Depth32FloatStencil8 = 2
    | TimestampQuery = 3
    | TextureCompressionBC = 4
    | TextureCompressionETC2 = 5
    | TextureCompressionASTC = 6
    | IndirectFirstInstance = 7
    | ShaderF16 = 8
    | RG11B10UfloatRenderable = 9
    | BGRA8UnormStorage = 10
    | Float32Filterable = 11
    | Float32Blendable = 12
    | Subgroups = 13
    | SubgroupsF16 = 14
    | DawnInternalUsages = 0
    | DawnMultiPlanarFormats = 1
    | DawnNative = 2
    | ChromiumExperimentalTimestampQueryInsidePasses = 3
    | ImplicitDeviceSynchronization = 4
    | ChromiumExperimentalImmediateData = 5
    | TransientAttachments = 6
    | MSAARenderToSingleSampled = 7
    | DualSourceBlending = 8
    | D3D11MultithreadProtected = 9
    | ANGLETextureSharing = 10
    | ChromiumExperimentalSubgroups = 11
    | ChromiumExperimentalSubgroupUniformControlFlow = 12
    | PixelLocalStorageCoherent = 13
    | PixelLocalStorageNonCoherent = 14
    | Unorm16TextureFormats = 15
    | Snorm16TextureFormats = 16
    | MultiPlanarFormatExtendedUsages = 17
    | MultiPlanarFormatP010 = 18
    | HostMappedPointer = 19
    | MultiPlanarRenderTargets = 20
    | MultiPlanarFormatNv12a = 21
    | FramebufferFetch = 22
    | BufferMapExtendedUsages = 23
    | AdapterPropertiesMemoryHeaps = 24
    | AdapterPropertiesD3D = 25
    | AdapterPropertiesVk = 26
    | R8UnormStorage = 27
    | FormatCapabilities = 28
    | DrmFormatCapabilities = 29
    | Norm16TextureFormats = 30
    | MultiPlanarFormatNv16 = 31
    | MultiPlanarFormatNv24 = 32
    | MultiPlanarFormatP210 = 33
    | MultiPlanarFormatP410 = 34
    | SharedTextureMemoryVkDedicatedAllocation = 35
    | SharedTextureMemoryAHardwareBuffer = 36
    | SharedTextureMemoryDmaBuf = 37
    | SharedTextureMemoryOpaqueFD = 38
    | SharedTextureMemoryZirconHandle = 39
    | SharedTextureMemoryDXGISharedHandle = 40
    | SharedTextureMemoryD3D11Texture2D = 41
    | SharedTextureMemoryIOSurface = 42
    | SharedTextureMemoryEGLImage = 43
    | SharedFenceVkSemaphoreOpaqueFD = 44
    | SharedFenceSyncFD = 45
    | SharedFenceVkSemaphoreZirconHandle = 46
    | SharedFenceDXGISharedHandle = 47
    | SharedFenceMTLSharedEvent = 48
    | SharedBufferMemoryD3D12Resource = 49
    | StaticSamplers = 50
    | YCbCrVulkanSamplers = 51
    | ShaderModuleCompilationOptions = 52
    | DawnLoadResolveTexture = 53
    | DawnPartialLoadResolveTexture = 54
    | MultiDrawIndirect = 55
    | ClipDistances = 56
type FilterMode =
    | Undefined = 0
    | Nearest = 1
    | Linear = 2
type FrontFace =
    | Undefined = 0
    | CCW = 1
    | CW = 2
type IndexFormat =
    | Undefined = 0
    | Uint16 = 1
    | Uint32 = 2
type CallbackMode =
    | WaitAnyOnly = 1
    | AllowProcessEvents = 2
    | AllowSpontaneous = 3
type WaitStatus =
    | Success = 1
    | TimedOut = 2
    | UnsupportedTimeout = 3
    | UnsupportedCount = 4
    | UnsupportedMixedSources = 5
    | Unknown = 6
type VertexStepMode =
    | VertexBufferNotUsed = 0
    | Undefined = 1
    | Vertex = 2
    | Instance = 3
type LoadOp =
    | Undefined = 0
    | Load = 1
    | Clear = 2
    | ExpandResolveTexture = 3
[<Flags>]
type MapMode =
    | None = 0L
    | Read = 1L
    | Write = 2L
type MipmapFilterMode =
    | Undefined = 0
    | Nearest = 1
    | Linear = 2
type StoreOp =
    | Undefined = 0
    | Store = 1
    | Discard = 2
type PowerPreference =
    | Undefined = 0
    | LowPower = 1
    | HighPerformance = 2
type PresentMode =
    | Fifo = 1
    | FifoRelaxed = 2
    | Immediate = 3
    | Mailbox = 4
type PrimitiveTopology =
    | Undefined = 0
    | PointList = 1
    | LineList = 2
    | LineStrip = 3
    | TriangleList = 4
    | TriangleStrip = 5
type QueryType =
    | Occlusion = 1
    | Timestamp = 2
type QueueWorkDoneStatus =
    | Success = 1
    | InstanceDropped = 2
    | Error = 3
    | Unknown = 4
    | DeviceLost = 5
type RequestDeviceStatus =
    | Success = 1
    | InstanceDropped = 2
    | Error = 3
    | Unknown = 4
[<Flags>]
type ShaderStage =
    | None = 0L
    | Vertex = 1L
    | Fragment = 2L
    | Compute = 4L
type StencilOperation =
    | Undefined = 0
    | Keep = 1
    | Zero = 2
    | Replace = 3
    | Invert = 4
    | IncrementClamp = 5
    | DecrementClamp = 6
    | IncrementWrap = 7
    | DecrementWrap = 8
type SType =
    | ShaderSourceSPIRV = 1
    | ShaderSourceWGSL = 2
    | RenderPassMaxDrawCount = 3
    | SurfaceSourceMetalLayer = 4
    | SurfaceSourceWindowsHWND = 5
    | SurfaceSourceXlibWindow = 6
    | SurfaceSourceWaylandSurface = 7
    | SurfaceSourceAndroidNativeWindow = 8
    | SurfaceSourceXCBWindow = 9
    | TextureBindingViewDimensionDescriptor = 0
    | SurfaceSourceCanvasHTMLSelector_Emscripten = 0
    | SurfaceDescriptorFromWindowsCoreWindow = 0
    | ExternalTextureBindingEntry = 1
    | ExternalTextureBindingLayout = 2
    | SurfaceDescriptorFromWindowsSwapChainPanel = 3
    | DawnTextureInternalUsageDescriptor = 4
    | DawnEncoderInternalUsageDescriptor = 5
    | DawnInstanceDescriptor = 6
    | DawnCacheDeviceDescriptor = 7
    | DawnAdapterPropertiesPowerPreference = 8
    | DawnBufferDescriptorErrorInfoFromWireClient = 9
    | DawnTogglesDescriptor = 10
    | DawnShaderModuleSPIRVOptionsDescriptor = 11
    | RequestAdapterOptionsLUID = 12
    | RequestAdapterOptionsGetGLProc = 13
    | RequestAdapterOptionsD3D11Device = 14
    | DawnRenderPassColorAttachmentRenderToSingleSampled = 15
    | RenderPassPixelLocalStorage = 16
    | PipelineLayoutPixelLocalStorage = 17
    | BufferHostMappedPointer = 18
    | DawnExperimentalSubgroupLimits = 19
    | AdapterPropertiesMemoryHeaps = 20
    | AdapterPropertiesD3D = 21
    | AdapterPropertiesVk = 22
    | DawnComputePipelineFullSubgroups = 23
    | DawnWireWGSLControl = 24
    | DawnWGSLBlocklist = 25
    | DrmFormatCapabilities = 26
    | ShaderModuleCompilationOptions = 27
    | ColorTargetStateExpandResolveTextureDawn = 28
    | RenderPassDescriptorExpandResolveRect = 29
    | SharedTextureMemoryVkDedicatedAllocationDescriptor = 30
    | SharedTextureMemoryAHardwareBufferDescriptor = 31
    | SharedTextureMemoryDmaBufDescriptor = 32
    | SharedTextureMemoryOpaqueFDDescriptor = 33
    | SharedTextureMemoryZirconHandleDescriptor = 34
    | SharedTextureMemoryDXGISharedHandleDescriptor = 35
    | SharedTextureMemoryD3D11Texture2DDescriptor = 36
    | SharedTextureMemoryIOSurfaceDescriptor = 37
    | SharedTextureMemoryEGLImageDescriptor = 38
    | SharedTextureMemoryInitializedBeginState = 39
    | SharedTextureMemoryInitializedEndState = 40
    | SharedTextureMemoryVkImageLayoutBeginState = 41
    | SharedTextureMemoryVkImageLayoutEndState = 42
    | SharedTextureMemoryD3DSwapchainBeginState = 43
    | SharedFenceVkSemaphoreOpaqueFDDescriptor = 44
    | SharedFenceVkSemaphoreOpaqueFDExportInfo = 45
    | SharedFenceSyncFDDescriptor = 46
    | SharedFenceSyncFDExportInfo = 47
    | SharedFenceVkSemaphoreZirconHandleDescriptor = 48
    | SharedFenceVkSemaphoreZirconHandleExportInfo = 49
    | SharedFenceDXGISharedHandleDescriptor = 50
    | SharedFenceDXGISharedHandleExportInfo = 51
    | SharedFenceMTLSharedEventDescriptor = 52
    | SharedFenceMTLSharedEventExportInfo = 53
    | SharedBufferMemoryD3D12ResourceDescriptor = 54
    | StaticSamplerBindingLayout = 55
    | YCbCrVkDescriptor = 56
    | SharedTextureMemoryAHardwareBufferProperties = 57
    | AHardwareBufferProperties = 58
    | DawnExperimentalImmediateDataLimits = 59
type SurfaceGetCurrentTextureStatus =
    | Success = 1
    | Timeout = 2
    | Outdated = 3
    | Lost = 4
    | OutOfMemory = 5
    | DeviceLost = 6
    | Error = 7
type TextureAspect =
    | Undefined = 0
    | All = 1
    | StencilOnly = 2
    | DepthOnly = 3
    | Plane0Only = 0
    | Plane1Only = 1
    | Plane2Only = 2
type TextureDimension =
    | Undefined = 0
    | D1D = 1
    | D2D = 2
    | D3D = 3
type TextureFormat =
    | Undefined = 0
    | R8Unorm = 1
    | R8Snorm = 2
    | R8Uint = 3
    | R8Sint = 4
    | R16Uint = 5
    | R16Sint = 6
    | R16Float = 7
    | RG8Unorm = 8
    | RG8Snorm = 9
    | RG8Uint = 10
    | RG8Sint = 11
    | R32Float = 12
    | R32Uint = 13
    | R32Sint = 14
    | RG16Uint = 15
    | RG16Sint = 16
    | RG16Float = 17
    | RGBA8Unorm = 18
    | RGBA8UnormSrgb = 19
    | RGBA8Snorm = 20
    | RGBA8Uint = 21
    | RGBA8Sint = 22
    | BGRA8Unorm = 23
    | BGRA8UnormSrgb = 24
    | RGB10A2Uint = 25
    | RGB10A2Unorm = 26
    | RG11B10Ufloat = 27
    | RGB9E5Ufloat = 28
    | RG32Float = 29
    | RG32Uint = 30
    | RG32Sint = 31
    | RGBA16Uint = 32
    | RGBA16Sint = 33
    | RGBA16Float = 34
    | RGBA32Float = 35
    | RGBA32Uint = 36
    | RGBA32Sint = 37
    | Stencil8 = 38
    | Depth16Unorm = 39
    | Depth24Plus = 40
    | Depth24PlusStencil8 = 41
    | Depth32Float = 42
    | Depth32FloatStencil8 = 43
    | BC1RGBAUnorm = 44
    | BC1RGBAUnormSrgb = 45
    | BC2RGBAUnorm = 46
    | BC2RGBAUnormSrgb = 47
    | BC3RGBAUnorm = 48
    | BC3RGBAUnormSrgb = 49
    | BC4RUnorm = 50
    | BC4RSnorm = 51
    | BC5RGUnorm = 52
    | BC5RGSnorm = 53
    | BC6HRGBUfloat = 54
    | BC6HRGBFloat = 55
    | BC7RGBAUnorm = 56
    | BC7RGBAUnormSrgb = 57
    | ETC2RGB8Unorm = 58
    | ETC2RGB8UnormSrgb = 59
    | ETC2RGB8A1Unorm = 60
    | ETC2RGB8A1UnormSrgb = 61
    | ETC2RGBA8Unorm = 62
    | ETC2RGBA8UnormSrgb = 63
    | EACR11Unorm = 64
    | EACR11Snorm = 65
    | EACRG11Unorm = 66
    | EACRG11Snorm = 67
    | ASTC4x4Unorm = 68
    | ASTC4x4UnormSrgb = 69
    | ASTC5x4Unorm = 70
    | ASTC5x4UnormSrgb = 71
    | ASTC5x5Unorm = 72
    | ASTC5x5UnormSrgb = 73
    | ASTC6x5Unorm = 74
    | ASTC6x5UnormSrgb = 75
    | ASTC6x6Unorm = 76
    | ASTC6x6UnormSrgb = 77
    | ASTC8x5Unorm = 78
    | ASTC8x5UnormSrgb = 79
    | ASTC8x6Unorm = 80
    | ASTC8x6UnormSrgb = 81
    | ASTC8x8Unorm = 82
    | ASTC8x8UnormSrgb = 83
    | ASTC10x5Unorm = 84
    | ASTC10x5UnormSrgb = 85
    | ASTC10x6Unorm = 86
    | ASTC10x6UnormSrgb = 87
    | ASTC10x8Unorm = 88
    | ASTC10x8UnormSrgb = 89
    | ASTC10x10Unorm = 90
    | ASTC10x10UnormSrgb = 91
    | ASTC12x10Unorm = 92
    | ASTC12x10UnormSrgb = 93
    | ASTC12x12Unorm = 94
    | ASTC12x12UnormSrgb = 95
    | R16Unorm = 0
    | RG16Unorm = 1
    | RGBA16Unorm = 2
    | R16Snorm = 3
    | RG16Snorm = 4
    | RGBA16Snorm = 5
    | R8BG8Biplanar420Unorm = 6
    | R10X6BG10X6Biplanar420Unorm = 7
    | R8BG8A8Triplanar420Unorm = 8
    | R8BG8Biplanar422Unorm = 9
    | R8BG8Biplanar444Unorm = 10
    | R10X6BG10X6Biplanar422Unorm = 11
    | R10X6BG10X6Biplanar444Unorm = 12
    | External = 13
[<Flags>]
type TextureUsage =
    | None = 0L
    | CopySrc = 1L
    | CopyDst = 2L
    | TextureBinding = 4L
    | StorageBinding = 8L
    | RenderAttachment = 16L
    | TransientAttachment = 32L
    | StorageAttachment = 64L
type TextureViewDimension =
    | Undefined = 0
    | D1D = 1
    | D2D = 2
    | D2DArray = 3
    | Cube = 4
    | CubeArray = 5
    | D3D = 6
type VertexFormat =
    | Uint8 = 1
    | Uint8x2 = 2
    | Uint8x4 = 3
    | Sint8 = 4
    | Sint8x2 = 5
    | Sint8x4 = 6
    | Unorm8 = 7
    | Unorm8x2 = 8
    | Unorm8x4 = 9
    | Snorm8 = 10
    | Snorm8x2 = 11
    | Snorm8x4 = 12
    | Uint16 = 13
    | Uint16x2 = 14
    | Uint16x4 = 15
    | Sint16 = 16
    | Sint16x2 = 17
    | Sint16x4 = 18
    | Unorm16 = 19
    | Unorm16x2 = 20
    | Unorm16x4 = 21
    | Snorm16 = 22
    | Snorm16x2 = 23
    | Snorm16x4 = 24
    | Float16 = 25
    | Float16x2 = 26
    | Float16x4 = 27
    | Float32 = 28
    | Float32x2 = 29
    | Float32x3 = 30
    | Float32x4 = 31
    | Uint32 = 32
    | Uint32x2 = 33
    | Uint32x3 = 34
    | Uint32x4 = 35
    | Sint32 = 36
    | Sint32x2 = 37
    | Sint32x3 = 38
    | Sint32x4 = 39
    | Unorm10_10_10_2 = 40
    | Unorm8x4BGRA = 41
type WGSLFeatureName =
    | ReadonlyAndReadwriteStorageTextures = 1
    | Packed4x8IntegerDotProduct = 2
    | UnrestrictedPointerParameters = 3
    | PointerCompositeAccess = 4
    | ChromiumTestingUnimplemented = 0
    | ChromiumTestingUnsafeExperimental = 1
    | ChromiumTestingExperimental = 2
    | ChromiumTestingShippedWithKillswitch = 3
    | ChromiumTestingShipped = 4
[<Flags>]
type HeapProperty =
    | DeviceLocal = 1L
    | HostVisible = 2L
    | HostCoherent = 4L
    | HostUncached = 8L
    | HostCached = 16L
